import { getExtensionOrgExportColumns } from '../extensions/tenancyRegistry';
import type { ExportColumnDecision, TenantExportPolicyRegistry, TenantExportTablePolicy } from './tenantExportPolicy';

type ColumnGroups = Readonly<{
  included: readonly string[];
  reviewedIncluded: readonly string[];
  excludedSensitive: readonly string[];
  excludedOpen: readonly string[];
  specific?: Readonly<Record<string, ExportColumnDecision>>;
}>;

const INCLUDED: ExportColumnDecision = { decision: 'include', rationale: 'Customer-owned tenant data included in the portable export contract.' };
const REVIEWED_INCLUDED: ExportColumnDecision = { decision: 'include', rationale: 'Security-adjacent operational identifier, status, timestamp, count, or integrity value reviewed as non-secret.', reviewedSensitiveName: true };
const EXCLUDED_SENSITIVE: ExportColumnDecision = { decision: 'exclude', rationale: 'Authentication, credential, capability, private-key, or verifier material is prohibited from tenant exports.', reviewedSensitiveName: true, openContainerReviewed: true };
const EXCLUDED_OPEN: ExportColumnDecision = { decision: 'exclude', rationale: 'Open-ended container content is excluded after review because it may embed credentials or capabilities.', reviewedSensitiveName: true, openContainerReviewed: true };

export function tablePolicy(
  organizationKey: 'id' | 'org_id',
  groups: ColumnGroups,
): TenantExportTablePolicy {
  const columns: Record<string, ExportColumnDecision> = {};
  const assign = (column: string, decision: ExportColumnDecision) => {
    if (Object.prototype.hasOwnProperty.call(columns, column)) {
      throw new Error(
        `[tenantExport] duplicate classification for column "${column}"`,
      );
    }
    columns[column] = decision;
  };

  for (const column of groups.included) assign(column, INCLUDED);
  for (const column of groups.reviewedIncluded) assign(column, REVIEWED_INCLUDED);
  for (const column of groups.excludedSensitive) assign(column, EXCLUDED_SENSITIVE);
  for (const column of groups.excludedOpen) assign(column, EXCLUDED_OPEN);
  for (const [column, decision] of Object.entries(groups.specific ?? {})) {
    assign(column, decision);
  }
  return { organizationKey, columns };
}

export const CORE_TENANT_EXPORT_POLICY: TenantExportPolicyRegistry = {
  "access_reviews": tablePolicy("org_id", {"included":["id","partner_id","org_id","name","description","status","reviewer_id","due_date","created_at","updated_at","completed_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "account_deletion_requests": tablePolicy("org_id", {"included":["id","user_id","org_id","reason","status","requested_at","process_by","processed_at","processed_by","admin_note","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "action_intents": tablePolicy("org_id", {"included":["id","org_id","partner_id","requested_by_user_id","requesting_api_key_id","source","requesting_client_label","action_name","action_version","argument_digest","target_summary","impact_summary","reason","risk_tier","connection_id","tenant_id","idempotency_key","correlation_id","status","created_at","expires_at","decided_at","decided_by_user_id","decided_assurance_level","decided_via","execution_started_at","executed_at","error_code","approval_scope","classification_version","approval_expires_at","release_by","effect_digest"],"reviewedIncluded":["origin_principal_kind","origin_principal_id"],"excludedSensitive":[],"excludedOpen":["arguments","result"]}),
  "agent_logs": tablePolicy("org_id", {"included":["id","device_id","org_id","timestamp","level","component","message","agent_version","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["fields"]}),
  "ai_action_plans": tablePolicy("org_id", {"included":["id","session_id","org_id","status","current_step_index","approved_by","approved_at","completed_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["steps"]}),
  "ai_budgets": tablePolicy("org_id", {"included":["id","org_id","enabled","monthly_budget_cents","daily_budget_cents","max_turns_per_session","messages_per_minute_per_user","messages_per_hour_per_org","approval_mode","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["allowed_models"]}),
  "ai_cost_usage": tablePolicy("org_id", {"included":["id","org_id","period","period_key","total_cost_cents","session_count","message_count","tool_execution_count","updated_at"],"reviewedIncluded":["input_tokens","output_tokens"],"excludedSensitive":[],"excludedOpen":[]}),
  "ai_screenshots": tablePolicy("org_id", {"included":["id","device_id","org_id","session_id","storage_key","width","height","size_bytes","captured_by","reason","expires_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "ai_sessions": tablePolicy("org_id", {"included":["id","org_id","user_id","device_id","status","type","title","model","system_prompt","total_cost_cents","turn_count","max_turns","sdk_session_id","last_activity_at","created_at","updated_at","flagged_at","flagged_by","flag_reason","delegant_m365_connection_id","client_user_id","workbook_name"],"reviewedIncluded":["total_input_tokens","total_output_tokens"],"excludedSensitive":[],"excludedOpen":["context_snapshot"]}),
  "alert_correlation_groups": tablePolicy("org_id", {"included":["id","org_id","group_key","root_alert_id","status","score","noise_reduction_percent","member_count","first_seen_at","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "alert_correlation_members": tablePolicy("org_id", {"included":["id","org_id","group_id","alert_id","role","confidence","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["evidence"]}),
  "alert_rules": tablePolicy("org_id", {"included":["id","org_id","partner_id","template_id","name","target_type","target_id","is_active","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["override_settings"]}),
  "alert_templates": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","category","severity","title_template","message_template","auto_resolve","cooldown_minutes","is_built_in","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["conditions","targets","auto_resolve_conditions"]}),
  "alerts": tablePolicy("org_id", {"included":["id","rule_id","device_id","org_id","config_policy_id","config_item_name","status","severity","title","message","triggered_at","acknowledged_at","acknowledged_by","resolved_at","resolved_by","resolution_note","suppressed_until","dismissed_at","dismissed_by","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["context"]}),
  "analytics_dashboards": tablePolicy("org_id", {"included":["id","org_id","name","description","is_default","is_system","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["layout"]}),
  "api_keys": tablePolicy("org_id", {"included":["id","org_id","name","key_prefix","expires_at","last_used_at","usage_count","rate_limit","created_by","created_at","updated_at","status","source","principal_type","principal_id"],"reviewedIncluded":[],"excludedSensitive":["key_hash"],"excludedOpen":["scopes"]}),
  "asset_checkouts": tablePolicy("org_id", {"included":["id","org_id","device_id","checked_out_to","checked_out_to_name","checked_out_at","expected_return_at","checked_in_at","checked_in_by","checkout_notes","checkin_notes","condition","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "audit_baseline_apply_approvals": tablePolicy("org_id", {"included":["id","org_id","baseline_id","requested_by","approved_by","status","expires_at","approved_at","consumed_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["request_payload"]}),
  "audit_baseline_results": tablePolicy("org_id", {"included":["id","org_id","device_id","baseline_id","compliant","score","checked_at","remediated_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["deviations"]}),
  "audit_baselines": tablePolicy("org_id", {"included":["id","org_id","name","os_type","profile","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["settings"]}),
  "audit_chain_anchors": tablePolicy("org_id", {"included":["anchor_seq","org_id","head_chain_seq","head_chain_checksum","entry_count","signature","signing_key_id","anchored_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "audit_log_chain": tablePolicy("org_id", {"included":["chain_seq","audit_id","org_id","content_checksum","prev_chain_checksum","chain_checksum","sealed_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "audit_logs": tablePolicy("org_id", {"included":["id","org_id","timestamp","actor_type","actor_id","actor_email","action","resource_type","resource_id","resource_name","ip_address","user_agent","result","error_message","checksum","prev_checksum","initiated_by"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "audit_policy_states": tablePolicy("org_id", {"included":["id","org_id","device_id","os_type","collected_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["settings","raw"]}),
  "audit_retention_policies": tablePolicy("org_id", {"included":["id","org_id","retention_days","archive_to_s3","last_cleanup_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "automation_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","enabled","enforcement","check_interval_minutes","remediation_script_id","last_evaluated_at","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["targets","rules"]}),
  "automation_run_device_results": tablePolicy("org_id", {"included":["id","run_id","device_id","org_id","status","started_at","completed_at","output","error","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "automations": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","enabled","on_failure","last_run_at","run_count","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["trigger","conditions","actions","notification_targets"]}),
  "backup_chains": tablePolicy("org_id", {"included":["id","org_id","device_id","config_id","chain_type","target_name","target_id","is_active","full_snapshot_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["chain_metadata"]}),
  "backup_configs": tablePolicy("org_id", {"included":["id","org_id","name","type","provider","provider_capabilities_checked_at","compression","encryption","is_active","is_default","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["encryption_key"],"excludedOpen":["provider_config","schedule","retention","provider_capabilities"]}),
  "backup_jobs": tablePolicy("org_id", {"included":["id","org_id","config_id","policy_id","feature_link_id","device_id","status","type","backup_mode","started_at","completed_at","total_size","transferred_size","file_count","error_count","error_log","snapshot_id","backup_type","last_progress_at","total_files","referenced_size","referenced_files","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["mode_targets","vss_metadata"]}),
  "backup_policies": tablePolicy("org_id", {"included":["id","org_id","config_id","name","enabled","legal_hold","legal_hold_reason","bandwidth_limit_mbps","backup_window_start","backup_window_end","priority","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["schedule","retention","targets","gfs_config"]}),
  "backup_profiles": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["selections"]}),
  "backup_sla_configs": tablePolicy("org_id", {"included":["id","org_id","name","rpo_target_minutes","rto_target_minutes","alert_on_breach","is_active","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["target_devices","target_groups"]}),
  "backup_sla_events": tablePolicy("org_id", {"included":["id","org_id","sla_config_id","device_id","event_type","detected_at","resolved_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "backup_snapshots": tablePolicy("org_id", {"included":["id","org_id","job_id","device_id","config_id","snapshot_id","label","location","timestamp","size","file_count","is_incremental","parent_snapshot_id","expires_at","storage_tier","is_immutable","immutable_until","legal_hold","legal_hold_reason","immutability_enforcement","requested_immutability_enforcement","immutability_fallback_reason","checksum_sha256","backup_type"],"reviewedIncluded":["encryption_key_id"],"excludedSensitive":[],"excludedOpen":["metadata","gfs_tags","hardware_profile","system_state_manifest"]}),
  "backup_verifications": tablePolicy("org_id", {"included":["id","org_id","device_id","backup_job_id","snapshot_id","verification_type","status","started_at","completed_at","restore_time_seconds","files_verified","files_failed","size_bytes","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "brain_device_context": tablePolicy("org_id", {"included":["id","org_id","device_id","context_type","summary","created_at","expires_at","resolved_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "browser_extensions": tablePolicy("org_id", {"included":["id","org_id","device_id","browser","extension_id","name","version","source","risk_level","enabled","first_seen_at","last_seen_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["permissions"]}),
  "browser_policies": tablePolicy("org_id", {"included":["id","org_id","name","target_type","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["allowed_extensions","blocked_extensions","required_extensions","settings","target_ids"]}),
  "browser_policy_violations": tablePolicy("org_id", {"included":["id","org_id","device_id","policy_id","violation_type","detected_at","resolved_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "c2c_backup_configs": tablePolicy("org_id", {"included":["id","org_id","connection_id","name","backup_scope","storage_config_id","is_active","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["target_users","schedule","retention"]}),
  "c2c_backup_items": tablePolicy("org_id", {"included":["id","org_id","config_id","job_id","item_type","external_id","user_email","subject_or_name","parent_path","storage_path","size_bytes","item_date","is_deleted","deleted_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "c2c_backup_jobs": tablePolicy("org_id", {"included":["id","org_id","config_id","status","started_at","completed_at","items_processed","items_new","items_updated","items_deleted","bytes_transferred","error_log","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["delta_token"],"excludedOpen":[]}),
  "c2c_connections": tablePolicy("org_id", {"included":["id","org_id","provider","display_name","auth_method","tenant_id","client_id","scopes","status","last_sync_at","created_at","updated_at"],"reviewedIncluded":["token_expires_at"],"excludedSensitive":["client_secret","refresh_token","access_token"],"excludedOpen":[]}),
  "c2c_consent_sessions": tablePolicy("org_id", {"included":["id","org_id","user_id","provider","display_name","scopes","redirect_url","expires_at","created_at"],"reviewedIncluded":[],"excludedSensitive":["state"],"excludedOpen":[]}),
  "capacity_predictions": tablePolicy("org_id", {"included":["id","org_id","device_id","metric_type","metric_name","current_value","predicted_value","prediction_date","confidence","growth_rate","days_to_threshold","threshold_type","model_type","training_data_days","calculated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "capacity_thresholds": tablePolicy("org_id", {"included":["id","org_id","name","metric_type","metric_name","warning_threshold","critical_threshold","prediction_window","growth_rate_threshold","target_type","target_ids","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "catalog_item_org_pricing": tablePolicy("org_id", {"included":["id","catalog_item_id","org_id","unit_price","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "cis_baseline_results": tablePolicy("org_id", {"included":["id","org_id","device_id","baseline_id","checked_at","total_checks","passed_checks","failed_checks","score","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["findings","summary"]}),
  "cis_baselines": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","os_type","benchmark_version","level","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["custom_exclusions","scan_schedule"]}),
  "cis_remediation_actions": tablePolicy("org_id", {"included":["id","org_id","device_id","baseline_id","baseline_result_id","check_id","action","status","approval_status","approved_by","approved_at","approval_note","requested_by","command_id","executed_at","rollback_hint","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details","before_state","after_state"]}),
  "client_ai_org_policies": tablePolicy("org_id", {"included":["id","org_id","enabled","user_access","write_mode","write_approval","daily_budget_cents","monthly_budget_cents","per_user_messages_per_minute","org_messages_per_hour","retention_days","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["selected_user_ids","allowed_providers","allowed_models","dlp_config","branding"]}),
  "client_ai_prompt_templates": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","prompt_body","category","hosts","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "client_ai_tenant_mappings": tablePolicy("org_id", {"included":["id","org_id","entra_tenant_id","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "client_ai_usage": tablePolicy("org_id", {"included":["id","org_id","client_user_id","period","period_key","total_cost_cents","session_count","message_count","updated_at"],"reviewedIncluded":["input_tokens","output_tokens"],"excludedSensitive":[],"excludedOpen":[]}),
  "config_policy_backup_settings": tablePolicy("org_id", {"included":["id","feature_link_id","org_id","partner_id","backup_mode","backup_profile_id","destination_config_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["schedule","retention","paths","targets"]}),
  "config_policy_onedrive_libraries": tablePolicy("org_id", {"included":["id","settings_id","org_id","library_id","display_name","site_url","site_id","web_id","list_id","targeting_mode","group_id","group_name","hive_scope","sort_order","enabled","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "config_policy_onedrive_settings": tablePolicy("org_id", {"included":["id","feature_link_id","org_id","silent_account_config","files_on_demand","kfm_silent_opt_in","kfm_block_opt_out","tenant_association_id","restart_on_change","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["kfm_folders"]}),
  "configuration_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","status","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "contact_external_links": tablePolicy("org_id", {"included":["id","contact_id","org_id","system","external_id","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  // Every column `included` is the POINT of #3258: the same PII sat in
  // organizations.billing_contact / sites.contact as unshaped jsonb, was
  // therefore classified excludedOpen, and was silently dropped from every
  // tenant export. Real columns follow the established convention for person
  // data (users.email/name/phone_number, tickets.submitter_email).
  "contacts": tablePolicy("org_id", {"included":["id","org_id","site_id","name","email","phone","mobile","title","roles","is_primary","notes","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "contract_billing_periods": tablePolicy("org_id", {"included":["id","contract_id","org_id","period_start","period_end","invoice_id","generated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "contract_documents": tablePolicy("org_id", {"included":["id","org_id","quote_id","quote_acceptance_id","contract_id","template_id","template_version_id","rendered_html","mime","byte_size","sha256","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["pdf_data"]}),
  "contract_lines": tablePolicy("org_id", {"included":["id","contract_id","org_id","line_type","description","catalog_item_id","unit_price","manual_quantity","site_id","taxable","sort_order","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "contract_renewal_notices": tablePolicy("org_id", {"included":["id","contract_id","org_id","end_date","kind","sent_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "contract_template_versions": tablePolicy("org_id", {"included":["id","template_id","org_id","partner_id","version_number","status","source_type","body_html","mime","byte_size","sha256","published_at","created_by","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["file_data","declared_variables"]}),
  "contract_templates": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","status","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "contracts": tablePolicy("org_id", {"included":["id","partner_id","org_id","name","status","billing_timing","interval_months","start_date","end_date","next_billing_at","auto_issue","auto_renew","renewal_term_months","renewal_notice_days","currency_code","notes","terms","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "custom_field_definitions": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","field_key","type","required","device_types","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["options","default_value"]}),
  "customer_email_domains": tablePolicy("org_id", {"included":["id","partner_id","org_id","domain","auto_create_contact","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "delegant_m365_connections": tablePolicy("org_id", {"included":["id","org_id","customer_label","customer_display_name","delegant_org_id","delegant_connection_id","m365_tenant_id","status","last_verified_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "deployment_invites": tablePolicy("org_id", {"included":["id","partner_id","org_id","enrollment_key_id","custom_message","sent_at","clicked_at","enrolled_at","device_id","status"],"reviewedIncluded":["invited_email","invited_by_api_key_id"],"excludedSensitive":[],"excludedOpen":[]}),
  "deployments": tablePolicy("org_id", {"included":["id","org_id","name","type","target_type","status","created_by","created_at","started_at","completed_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["payload","target_config","schedule","rollout_config"]}),
  "device_boot_metrics": tablePolicy("org_id", {"included":["id","device_id","org_id","boot_timestamp","bios_seconds","os_loader_seconds","desktop_ready_seconds","total_boot_seconds","startup_item_count","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["startup_items"]}),
  "device_change_log": tablePolicy("org_id", {"included":["id","device_id","org_id","fingerprint","timestamp","change_type","change_action","subject","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["before_value","after_value","details"]}),
  "device_config_state": tablePolicy("org_id", {"included":["device_id","org_id","file_path","config_key","collected_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["config_value"],"excludedOpen":[]}),
  "device_connections": tablePolicy("org_id", {"included":["id","device_id","org_id","protocol","local_addr","local_port","remote_addr","remote_port","state","pid","process_name","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_disks": tablePolicy("org_id", {"included":["id","device_id","org_id","mount_point","device","fs_type","total_gb","used_gb","free_gb","used_percent","health","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_event_logs": tablePolicy("org_id", {"included":["id","device_id","org_id","timestamp","level","category","source","event_id","message","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"],"specific":{"search_vector":{"decision":"exclude","rationale":"PostgreSQL tsvector search-index data is derived from event content and is not needed in a portable tenant export."}}}),
  "device_filesystem_cleanup_runs": tablePolicy("org_id", {"included":["id","device_id","org_id","requested_by","requested_at","approved_at","bytes_reclaimed","status","error","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["plan","executed_actions"]}),
  "device_filesystem_scan_state": tablePolicy("org_id", {"included":["device_id","org_id","last_run_mode","last_baseline_completed_at","last_disk_used_percent","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["checkpoint","aggregate","hot_directories"]}),
  "device_filesystem_snapshots": tablePolicy("org_id", {"included":["id","device_id","org_id","captured_at","trigger","partial","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["summary","largest_files","largest_dirs","temp_accumulation","old_downloads","unrotated_logs","trash_usage","duplicate_candidates","cleanup_candidates","errors","raw_payload"]}),
  "device_group_memberships": tablePolicy("org_id", {"included":["device_id","group_id","org_id","is_pinned","added_at","added_by"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_groups": tablePolicy("org_id", {"included":["id","org_id","site_id","name","type","filter_fields_used","parent_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["rules","filter_conditions"]}),
  "device_hardware": tablePolicy("org_id", {"included":["device_id","org_id","cpu_model","cpu_cores","cpu_threads","ram_total_mb","disk_total_gb","gpu_model","serial_number","manufacturer","model","motherboard_manufacturer","motherboard_product","motherboard_version","bios_version","updated_at","partner_export_updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_ip_history": tablePolicy("org_id", {"included":["id","device_id","org_id","interface_name","ip_address","ip_type","assignment_type","mac_address","subnet_mask","gateway","dns_servers","first_seen","last_seen","is_active","deactivated_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_link_groups": tablePolicy("org_id", {"included":["id","org_id","kind","name","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_metrics": tablePolicy("org_id", {"included":["device_id","org_id","timestamp","cpu_percent","ram_percent","ram_used_mb","disk_percent","disk_used_gb","disk_activity_available","disk_read_bytes","disk_write_bytes","disk_read_bps","disk_write_bps","disk_read_ops","disk_write_ops","network_in_bytes","network_out_bytes","bandwidth_in_bps","bandwidth_out_bps","process_count"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["interface_stats","custom_metrics"]}),
  "device_mtls_certificates": tablePolicy("org_id", {"included":["id","org_id","device_id","legacy_provenance","state","issued_at","expires_at","activation_expires_at","activated_at","revoked_at","revoke_attempts","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["provider_certificate_id","serial_number","fingerprint_sha256","public_key_spki","last_revoke_error","next_revoke_attempt_at"],"excludedOpen":[]}),
  "device_network": tablePolicy("org_id", {"included":["id","device_id","org_id","interface_name","mac_address","ip_address","ip_type","is_primary","public_ip","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_patches": tablePolicy("org_id", {"included":["id","device_id","org_id","patch_id","status","installed_at","installed_version","last_checked_at","failure_count","last_error","rollback_available","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_process_samples": tablePolicy("org_id", {"included":["device_id","org_id","timestamp","agent_timestamp"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["top_processes"]}),
  "device_recovery_keys": tablePolicy("org_id", {"included":["id","device_id","org_id","key_type","volume_mount","protector_id","key_fingerprint","status","escrowed_at","superseded_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["encrypted_key"],"excludedOpen":[]}),
  "device_registry_state": tablePolicy("org_id", {"included":["device_id","org_id","registry_path","value_name","value_type","collected_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["value_data"],"excludedOpen":[]}),
  "device_reliability": tablePolicy("org_id", {"included":["device_id","org_id","computed_at","reliability_score","uptime_score","crash_score","hang_score","service_failure_score","hardware_error_score","uptime_7d","uptime_30d","uptime_90d","crash_count_7d","crash_count_30d","crash_count_90d","hang_count_7d","hang_count_30d","hang_count_90d","service_failure_count_7d","service_failure_count_30d","hardware_error_count_7d","hardware_error_count_30d","mtbf_hours","trend_direction","trend_confidence"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["top_issues","details"]}),
  "device_reliability_history": tablePolicy("org_id", {"included":["id","device_id","org_id","collected_at","uptime_seconds","boot_time"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["crash_events","app_hangs","service_failures","hardware_errors","raw_metrics"]}),
  "device_sessions": tablePolicy("org_id", {"included":["id","org_id","device_id","username","session_type","os_session_id","login_at","logout_at","duration_seconds","idle_minutes","activity_state","login_performance_seconds","is_active","last_activity_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "device_vulnerabilities": tablePolicy("org_id", {"included":["id","org_id","device_id","vulnerability_id","software_inventory_id","status","risk_score","match_confidence","detected_at","resolved_at","mitigation_note","accepted_by","accepted_until","ticket_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "device_warranty": tablePolicy("org_id", {"included":["id","device_id","org_id","manufacturer","serial_number","status","warranty_start_date","warranty_end_date","is_subscription","data_source","last_sync_at","last_sync_error","next_sync_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["entitlements"]}),
  "devices": tablePolicy("org_id", {"included":["id","org_id","site_id","agent_id","mtls_cert_serial_number","mtls_cert_expires_at","mtls_cert_issued_at","mtls_cert_cf_id","quarantined_at","quarantined_reason","last_seen_ip","enrollment_ip","hostname","display_name","os_type","device_role","device_role_source","is_ephemeral","is_virtual","virtualization_platform","os_version","os_build","architecture","agent_version","status","last_seen_at","enrolled_at","enrolled_by","link_group_id","link_group_role","tags","last_user","uptime_seconds","is_headless","pending_reboot","watchdog_status","watchdog_last_seen","watchdog_version","backup_version","agent_server_url","agent_edition","migration_required","helper_lifecycle_mode","main_agent_silent_since","outbound_network_policy_version","uninstall_intent_at","possible_replacement_of_device_id","created_at","updated_at","partner_export_updated_at"],"reviewedIncluded":["token_issued_at","previous_token_expires_at","watchdog_token_issued_at","previous_watchdog_token_expires_at","helper_token_issued_at","previous_helper_token_expires_at","pending_token_expires_at","agent_token_suspended_at","agent_token_suspended_reason"],"excludedSensitive":["agent_token_hash","previous_token_hash","watchdog_token_hash","previous_watchdog_token_hash","helper_token_hash","previous_helper_token_hash","pending_token_hash","pending_watchdog_token_hash","pending_helper_token_hash"],"excludedOpen":["custom_fields","management_posture","tcc_permissions","desktop_access","battery_status","active_vpns"]}),
  "discovered_assets": tablePolicy("org_id", {"included":["id","org_id","site_id","ip_address","mac_address","hostname","label","netbios_name","asset_type","approval_status","is_online","approved_by","approved_at","dismissed_by","dismissed_at","manufacturer","model","response_time_ms","linked_device_id","link_source","auto_link_suppressed_at","type_source","detected_asset_type","detected_type_source","first_seen_at","last_seen_at","last_job_id","discovery_methods","notes","tags","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["open_ports","os_fingerprint","snmp_data"]}),
  "discovery_jobs": tablePolicy("org_id", {"included":["id","profile_id","org_id","site_id","agent_id","status","scheduled_at","started_at","completed_at","hosts_scanned","hosts_discovered","new_assets","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["errors"]}),
  "discovery_profiles": tablePolicy("org_id", {"included":["id","org_id","site_id","name","description","enabled","subnets","exclude_ips","methods","snmp_communities","deep_scan","identify_os","resolve_hostnames","timeout","concurrency","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["port_ranges","snmp_credentials","schedule","alert_settings"]}),
  "dns_event_aggregations": tablePolicy("org_id", {"included":["id","org_id","date","integration_id","device_id","domain","category","total_queries","blocked_queries","allowed_queries"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "dns_filter_integrations": tablePolicy("org_id", {"included":["id","org_id","provider","name","description","is_active","last_sync","last_sync_status","last_sync_error","total_events_processed","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["api_key","api_secret"],"excludedOpen":["config"]}),
  "dns_policies": tablePolicy("org_id", {"included":["id","org_id","integration_id","name","description","type","sync_status","last_synced","sync_error","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["domains","categories"]}),
  "dns_security_events": tablePolicy("org_id", {"included":["id","org_id","integration_id","device_id","timestamp","domain","query_type","action","category","threat_type","threat_score","source_ip","source_hostname","provider_event_id","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "dr_executions": tablePolicy("org_id", {"included":["id","plan_id","org_id","execution_type","status","started_at","completed_at","initiated_by","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["results"]}),
  "dr_plan_groups": tablePolicy("org_id", {"included":["id","plan_id","org_id","name","sequence","depends_on_group_id","estimated_duration_minutes"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["devices","restore_config"]}),
  "dr_plans": tablePolicy("org_id", {"included":["id","org_id","name","description","status","rpo_target_minutes","rto_target_minutes","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "elevation_audit": tablePolicy("org_id", {"included":["id","org_id","elevation_request_id","event_type","actor","actor_user_id","occurred_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "elevation_requests": tablePolicy("org_id", {"included":["id","org_id","site_id","partner_id","device_id","flow_type","subject_user_id","subject_username","reason","target_executable_path","target_executable_signer","target_publisher","status","requested_at","approved_at","expires_at","expired_at","revoked_at","revoked_by_user_id","revoked_reason","approved_by_user_id","denied_by_user_id","denial_reason","parent_approval_id","software_policy_match_id","execution_id","tool_name","action_digest","risk_tier","decided_assurance_level","decided_via","authenticator_device_id","session_started_at","session_ended_at","client_ip","user_agent","created_at","updated_at"],"reviewedIncluded":["target_executable_hash"],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "enrollment_keys": tablePolicy("org_id", {"included":["id","org_id","site_id","name","usage_count","max_usage","expires_at","created_by","created_at","installer_platform","support_session_id"],"reviewedIncluded":["bootstrap_token_id"],"excludedSensitive":["key","key_secret_hash","short_code"],"excludedOpen":[]}),
  "escalation_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["steps"]}),
  "event_bus_events": tablePolicy("org_id", {"included":["id","org_id","event_type","source","priority","processed_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["payload","metadata"]}),
  "executive_summaries": tablePolicy("org_id", {"included":["id","org_id","period_type","period_start","period_end","generated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["device_stats","alert_stats","patch_stats","sla_stats","trends","highlights"]}),
  "fleet_finding_devices": tablePolicy("org_id", {"included":["finding_id","org_id","device_id","source_kind","source_row_id","first_seen_at","last_seen_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["member_evidence"]}),
  "fleet_findings": tablePolicy("org_id", {"included":["id","org_id","kind","semantic_key","algorithm_version","status","severity","title","summary","device_count","revision","first_seen_at","last_seen_at","last_reconciled_at","acknowledged_at","acknowledged_by","dismissed_at","dismissed_by","dismiss_notes","resolved_at","resolution_reason","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["evidence"]}),
  "fleet_remediation_run_targets": tablePolicy("org_id", {"included":["run_id","org_id","target_device_uuid","hostname_snapshot","site_id_snapshot","status","device_command_id","skip_reason","queued_at","completed_at"],"reviewedIncluded":[],"excludedSensitive":["result_summary"],"excludedOpen":[]}),
  "fleet_remediation_runs": tablePolicy("org_id", {"included":["id","org_id","finding_id","finding_revision","action_kind","script_id","command_type","status","target_count","succeeded_count","failed_count","skipped_count","created_by","created_at","started_at","completed_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["parameter_snapshot"]}),
  "google_workspace_connections": tablePolicy("org_id", {"included":["id","org_id","customer_domain","admin_email","service_account_email","status","created_by","last_verified_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["service_account_key"],"excludedOpen":[]}),
  "group_membership_log": tablePolicy("org_id", {"included":["id","group_id","device_id","org_id","action","reason","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "huntress_agents": tablePolicy("org_id", {"included":["id","org_id","integration_id","huntress_agent_id","device_id","hostname","platform","status","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "huntress_incidents": tablePolicy("org_id", {"included":["id","org_id","integration_id","device_id","huntress_incident_id","severity","category","title","description","recommendation","status","reported_at","resolved_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "huntress_integrations": tablePolicy("org_id", {"included":["id","partner_id","org_id","name","account_id","api_base_url","is_active","last_sync_at","last_sync_status","last_sync_error","last_sync_agents","last_sync_incidents","last_sync_orgs","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["api_key_encrypted","account_key_encrypted","webhook_secret_encrypted"],"excludedOpen":[]}),
  "huntress_org_mappings": tablePolicy("org_id", {"included":["id","integration_id","partner_id","huntress_org_id","huntress_org_name","huntress_org_key","huntress_account_id","org_id","agents_count","incidents_count","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "hyperv_vms": tablePolicy("org_id", {"included":["id","org_id","device_id","vm_id","vm_name","generation","state","memory_mb","processor_count","rct_enabled","has_passthrough_disks","notes","last_discovered_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["vhd_paths","checkpoints"]}),
  "incident_actions": tablePolicy("org_id", {"included":["id","incident_id","org_id","action_type","description","executed_by","status","reversible","reversed","approval_ref","executed_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["result"]}),
  "incident_evidence": tablePolicy("org_id", {"included":["id","incident_id","org_id","evidence_type","description","collected_at","collected_by","storage_path","created_at"],"reviewedIncluded":["hash","hash_algorithm"],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "incidents": tablePolicy("org_id", {"included":["id","org_id","title","classification","severity","status","summary","source_type","source_ref","assigned_to","detected_at","contained_at","resolved_at","closed_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["related_alerts","affected_devices","affected_users","timeline"]}),
    // usage_kind joins the plain included set: it is a three-value enum recording
  // which mint path issued the token ('capacity' / 'per_download' /
  // 'legacy_unknown'), the same kind of non-secret classifier as
  // installer_platform.
  "installer_bootstrap_tokens": tablePolicy("org_id", {"included":["id","org_id","parent_enrollment_key_id","site_id","max_usage","consumed_count","created_by","created_at","expires_at","consumed_at","consumed_from_ip","installer_platform","usage_kind"],"reviewedIncluded":[],"excludedSensitive":["token"],"excludedOpen":[]}),
  "invoice_documents": tablePolicy("org_id", {"included":["id","invoice_id","org_id","sha256","generated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["pdf"]}),
  "invoice_lines": tablePolicy("org_id", {"included":["id","invoice_id","org_id","source_type","source_id","catalog_item_id","parent_line_id","ticket_id","name","description","quantity","unit_price","cost_basis","revenue_allocation","taxable","customer_visible","line_total","is_unapproved_time","sort_order","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "invoice_payments": tablePolicy("org_id", {"included":["id","invoice_id","org_id","amount","method","reference","received_at","recorded_by","note","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "invoice_stripe_payments": tablePolicy("org_id", {"included":["id","org_id","invoice_id","invoice_payment_id","stripe_account_id","stripe_object_type","stripe_object_id","stripe_payment_intent_id","amount","currency","status","last_event_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "invoices": tablePolicy("org_id", {"included":["id","partner_id","org_id","site_id","invoice_number","status","currency_code","issue_date","due_date","subtotal","tax_rate","tax_total","total","amount_paid","balance","deposit_due","bill_to_name","bill_to_tax_id","bill_to_tax_exempt","notes","terms","terms_and_conditions","sent_at","first_viewed_at","viewed_at","paid_at","marked_overdue_at","voided_at","void_reason","replaces_invoice_id","replaced_by_invoice_id","pdf_document_ref","pdf_sha256","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["bill_to_address","seller_snapshot"]}),
  "local_vaults": tablePolicy("org_id", {"included":["id","org_id","device_id","vault_path","vault_type","is_active","retention_count","last_sync_at","last_sync_status","last_sync_snapshot_id","sync_size_bytes","last_sync_error","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "log_correlation_rules": tablePolicy("org_id", {"included":["id","org_id","name","description","pattern","is_regex","min_occurrences","min_devices","time_window","severity","alert_on_match","is_active","last_matched_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "log_correlations": tablePolicy("org_id", {"included":["id","org_id","rule_id","pattern","first_seen","last_seen","occurrences","alert_id","status","resolved_at","resolved_by","notes","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["affected_devices","sample_logs"]}),
  "log_search_queries": tablePolicy("org_id", {"included":["id","org_id","name","description","created_by","is_shared","run_count","last_run_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["filters"]}),
  // delegated_user_object_id / consent_generation join the plain included set: an Entra
  // object id is the same kind of customer-tenant identifier as tenant_id and user_id, and
  // the generation counter is a monotonic integer like permission_manifest_version.
  // observed_delegated_scopes is excludedOpen, matching observed_grants — it is jsonb, and
  // its content is a list of granted capabilities, which is exactly what the open-container
  // exclusion exists for.
  "m365_connections": tablePolicy("org_id", {"included":["id","org_id","user_id","tenant_id","client_id","profile","auth_mode","permission_manifest_version","consent_attempt_id","delegated_user_object_id","consent_generation","grants_verified_at","display_name","status","consented_at","last_verified_at","expires_at","revoked_at","last_error_code","created_by","created_at","updated_at"],"reviewedIncluded":["credential_domain","credential_version"],"excludedSensitive":["client_secret","vault_ref"],"excludedOpen":["observed_grants","observed_delegated_scopes"]}),
  "m365_consent_sessions": tablePolicy("org_id", {"included":["id","phase","connection_id","org_id","profile","consent_attempt_id","user_id","expires_at","created_at"],"reviewedIncluded":[],"excludedSensitive":["state_hash","tenant_hint_hash","nonce","code_verifier"],"excludedOpen":[]}),
  "maintenance_windows": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","start_time","end_time","timezone","recurrence","target_type","site_ids","group_ids","device_ids","suppress_alerts","suppress_patching","suppress_automations","suppress_scripts","allowed_alert_severities","status","notify_before","notify_on_start","notify_on_end","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["recurrence_rule","allowed_actions","notification_channels"]}),
  "metric_anomalies": tablePolicy("org_id", {"included":["id","org_id","device_id","source_table","metric_type","metric_name","anomaly_type","status","window_start","window_end","bucket_seconds","observed_value","baseline_value","baseline_min","baseline_max","score","confidence","sample_count","linked_alert_id","linked_correlation_group_id","detected_at","resolved_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["baseline_summary","evidence"]}),
  "metric_anomaly_candidates": tablePolicy("org_id", {"included":["id","org_id","device_id","source_table","metric_type","metric_name","model_version","anomaly_type","window_start","window_end","bucket_seconds","observed_value","baseline_value","baseline_min","baseline_max","score","confidence","sample_count","detected_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["baseline_summary","evidence"]}),
  "metric_rollups": tablePolicy("org_id", {"included":["org_id","source_table","device_id","metric_type","metric_name","bucket_start","bucket_seconds","avg_value","min_value","max_value","p95_value","sum_value","sample_count","gap_seconds","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "metric_rollups_default": tablePolicy("org_id", {"included":["org_id","source_table","device_id","metric_type","metric_name","bucket_start","bucket_seconds","avg_value","min_value","max_value","p95_value","sum_value","sample_count","gap_seconds","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "ml_feedback_events": tablePolicy("org_id", {"included":["id","org_id","source_type","source_id","event_type","dedupe_key","actor_user_id","outcome","confidence","occurred_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "network_baselines": tablePolicy("org_id", {"included":["id","org_id","site_id","subnet","last_scan_at","last_scan_job_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["known_devices","scan_schedule","alert_settings"]}),
  "network_change_events": tablePolicy("org_id", {"included":["id","org_id","site_id","baseline_id","profile_id","event_type","ip_address","mac_address","hostname","asset_type","detected_at","acknowledged","acknowledged_by","acknowledged_at","alert_id","linked_device_id","notes","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["previous_state","current_state"]}),
  "network_monitors": tablePolicy("org_id", {"included":["id","org_id","asset_id","name","monitor_type","target","polling_interval","timeout","is_active","last_checked","last_status","last_response_ms","last_error","consecutive_failures","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["config"]}),
  "network_topology": tablePolicy("org_id", {"included":["id","org_id","site_id","source_type","source_id","target_type","target_id","connection_type","interface_name","vlan","bandwidth","latency","method","confidence","created_by","first_seen_at","last_verified_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "notification_channels": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","type","enabled","last_tested_at","last_test_status","throttle_max_per_window","throttle_window_seconds","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["config","templates"]}),
  "notification_routing_rules": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","priority","enabled","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["conditions","channel_ids"]}),
  "oauth_authorization_codes": tablePolicy("org_id", {"included":["id","user_id","client_id","partner_id","org_id","expires_at","consumed_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["payload"]}),
  "oauth_client_blocks": tablePolicy("org_id", {"included":["id","org_id","client_id","blocked_at","blocked_by_user_id","blocked_reason","blocked_until","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "oauth_grants": tablePolicy("org_id", {"included":["id","account_id","client_id","partner_id","org_id","expires_at","created_at","revoked_at","revoked_by_user_id","revoked_reason"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["payload"]}),
  "oauth_refresh_tokens": tablePolicy("org_id", {"included":["id","user_id","client_id","partner_id","org_id","expires_at","revoked_at","created_at","last_used_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["payload"]}),
  "onedrive_device_state": tablePolicy("org_id", {"included":["device_id","org_id","signed_in","onedrive_version","files_on_demand_on","last_reported_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["kfm_folder_states","mounted_libraries","entitled_libraries","signed_in_upns","drift_entries"]}),
  "org_ticket_settings": tablePolicy("org_id", {"included":["id","org_id","default_hourly_rate","default_billable","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["sla_overrides"]}),
  "organization_external_links": tablePolicy("org_id", {"included":["id","org_id","partner_id","system","external_id","label","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "organization_users": tablePolicy("org_id", {"included":["id","org_id","user_id","role_id","site_ids","device_group_ids","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "pam_org_config": tablePolicy("org_id", {"included":["id","org_id","default_unmatched_verdict","uac_interception_enabled","updated_by_user_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "pam_rules": tablePolicy("org_id", {"included":["id","org_id","site_id","name","description","enabled","priority","match_signer","match_signer_thumbprint","match_signer_group_id","match_path_glob","match_parent_image","match_command_line","match_user","match_ad_group","match_tool_name","match_risk_tier","verdict","approval_duration_minutes","created_by_user_id","created_at","updated_at"],"reviewedIncluded":["match_hash"],"excludedSensitive":[],"excludedOpen":["match_negate","time_window"]}),
  "pam_signer_groups": tablePolicy("org_id", {"included":["id","org_id","name","description","created_by_user_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["signers"]}),
  "patch_compliance_reports": tablePolicy("org_id", {"included":["id","org_id","requested_by","status","format","source","severity","row_count","output_path","error_message","started_at","completed_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["summary"]}),
  "patch_compliance_snapshots": tablePolicy("org_id", {"included":["id","org_id","ring_id","snapshot_date","total_devices","compliant_devices","non_compliant_devices","critical_missing","important_missing","patches_pending_approval","patches_installed_24h","failed_installs_24h","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details_by_category"]}),
  "patch_jobs": tablePolicy("org_id", {"included":["id","org_id","policy_id","ring_id","config_policy_id","name","status","scheduled_at","started_at","completed_at","devices_total","devices_completed","devices_failed","devices_pending","created_by","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["patches","targets"]}),
  "pax8_company_mappings": tablePolicy("org_id", {"included":["id","integration_id","partner_id","pax8_company_id","pax8_company_name","status","org_id","ignored","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "pax8_contract_line_links": tablePolicy("org_id", {"included":["id","integration_id","partner_id","org_id","subscription_snapshot_id","contract_line_id","sync_enabled","last_applied_quantity","last_applied_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "pax8_order_lines": tablePolicy("org_id", {"included":["id","order_id","partner_id","org_id","action","submit_state","pax8_product_id","catalog_item_id","billing_term","commitment_term_id","quantity","authorized_baseline_quantity","target_subscription_id","cancel_date","result_subscription_id","contract_line_id","source_quote_line_id","error","sort_order","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["provisioning_details"]}),
  "pax8_orders": tablePolicy("org_id", {"included":["id","integration_id","partner_id","org_id","pax8_company_id","status","source","source_quote_id","dedupe_key","pax8_order_id","error","created_by","submitted_by","submitted_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "pax8_subscription_snapshots": tablePolicy("org_id", {"included":["id","integration_id","partner_id","pax8_company_id","org_id","pax8_subscription_id","product_id","product_name","vendor_name","vendor_sku_id","status","billing_term","quantity","quantity_known","unit_price","unit_cost","currency_code","start_date","end_date","billing_start","commitment_term_end_date","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["raw"]}),
  "peripheral_events": tablePolicy("org_id", {"included":["id","org_id","device_id","policy_id","source_event_id","event_type","peripheral_type","vendor","product","serial_number","occurred_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "peripheral_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","device_class","action","target_type","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["target_ids","exceptions"]}),
  "playbook_definitions": tablePolicy("org_id", {"included":["id","org_id","name","description","is_built_in","is_active","category","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["steps","trigger_conditions","required_permissions"]}),
  "playbook_executions": tablePolicy("org_id", {"included":["id","org_id","device_id","playbook_id","status","current_step_index","error_message","rollback_executed","started_at","completed_at","triggered_by","triggered_by_user_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["steps","context"]}),
  "plugin_installations": tablePolicy("org_id", {"included":["id","org_id","catalog_id","version","status","enabled","sandbox_enabled","installed_at","installed_by","last_active_at","error_message","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["config","permissions","resource_limits"]}),
  "plugin_instances": tablePolicy("org_id", {"included":["id","plugin_id","org_id","enabled","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["config"]}),
  "plugins": tablePolicy("org_id", {"included":["id","org_id","name","slug","version","description","author","homepage","manifest_url","entry_point","status","is_system","installed_at","updated_at","error_message","last_active_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["permissions","hooks","settings"]}),
  "portal_branding": tablePolicy("org_id", {"included":["id","org_id","logo_url","favicon_url","primary_color","secondary_color","accent_color","custom_domain","domain_verified","welcome_message","support_email","support_phone","footer_text","custom_css","enable_tickets","enable_asset_checkout","enable_self_service","created_at","updated_at"],"reviewedIncluded":["enable_password_reset"],"excludedSensitive":[],"excludedOpen":[]}),
  "portal_users": tablePolicy("org_id", {"included":["id","org_id","email","name","entra_oid","entra_tenant_id","auth_method","linked_user_id","contact_id","receive_notifications","last_login_at","status","created_at","updated_at"],"reviewedIncluded":["invited_by","invited_at"],"excludedSensitive":["password_hash"],"excludedOpen":[]}),
  "provision_credential_handles": tablePolicy("org_id", {"included":["id","org_id","device_id","created_by","created_at","expires_at","consumed_at","consumed_from_ip"],"reviewedIncluded":[],"excludedSensitive":["token"],"excludedOpen":["credentials"]}),
  // partner_id (epic #2135, 2026-08-17): dual ownership — org_id XOR partner_id.
  // A tenant identifier like org_id, so `included`. Note the org export only
  // ever emits ORG-owned rows (the exporter filters on org_id), so a
  // partner-owned connection never appears in a customer's export — correct:
  // it is the MSP's credential, not the customer's data.
  "psa_connections": tablePolicy("org_id", {"included":["id","org_id","partner_id","provider","name","enabled","last_sync_at","last_sync_status","last_sync_error","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["credentials","settings","sync_settings"]}),
  "quote_acceptances": tablePolicy("org_id", {"included":["id","quote_id","org_id","signer_name","signer_email","signed_at","ip_address","user_agent","quote_sha256","created_at"],"reviewedIncluded":[],"excludedSensitive":["acceptance_token_jti"],"excludedOpen":[]}),
  "quote_blocks": tablePolicy("org_id", {"included":["id","quote_id","org_id","block_type","sort_order","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["content"]}),
  "quote_images": tablePolicy("org_id", {"included":["id","quote_id","org_id","mime","byte_size","sha256","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["image_data"]}),
  "quote_lines": tablePolicy("org_id", {"included":["id","quote_id","block_id","org_id","source_type","catalog_item_id","parent_line_id","name","description","quantity","unit_price","taxable","customer_visible","line_total","recurrence","term_months","billing_frequency","unit_cost","deposit_eligible","item_type","sku","part_number","procurement_source","vendor_sku","manufacturer","image_id","sort_order","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "quote_order_lines": tablePolicy("org_id", {"included":["id","order_id","quote_id","org_id","quote_line_id","ordered_qty","received_qty","tracking_number","eta","received_at","cancelled_at","notes","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "quote_orders": tablePolicy("org_id", {"included":["id","quote_id","org_id","procurement_source","vendor_name","order_ref","ordered_by","ordered_at","notes","client_request_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "quote_recipients": tablePolicy("org_id", {"included":["id","quote_id","org_id","email","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "quotes": tablePolicy("org_id", {"included":["id","partner_id","org_id","site_id","quote_number","title","status","currency_code","issue_date","expiry_date","accepted_at","declined_at","converted_at","subtotal","tax_rate","tax_total","total","one_time_total","monthly_recurring_total","annual_recurring_total","deposit_type","deposit_percent","deposit_amount","bill_to_name","bill_to_tax_id","intro_notes","terms","terms_and_conditions","decline_reason","converted_invoice_id","pdf_document_ref","pdf_sha256","sent_at","send_scheduled_at","send_job_id","send_email_reason","first_viewed_at","viewed_at","public_response_jti","public_response_consumed_at","public_response_outcome","public_link_revoked_at","created_by","created_at","updated_at"],"reviewedIncluded":["public_token_version"],"excludedSensitive":[],"excludedOpen":["bill_to_address","seller_snapshot","cover_page"]}),
  "recovery_boot_media_artifacts": tablePolicy("org_id", {"included":["id","org_id","snapshot_id","bundle_artifact_id","platform","architecture","media_type","status","storage_key","checksum_sha256","checksum_storage_key","signature_format","signature_storage_key","signing_key_id","created_by","created_at","signed_at","completed_at"],"reviewedIncluded":["token_id"],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "recovery_key_access_events": tablePolicy("org_id", {"included":["id","key_id","device_id","org_id","user_id","user_email","action","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "recovery_media_artifacts": tablePolicy("org_id", {"included":["id","org_id","snapshot_id","platform","architecture","status","storage_key","checksum_sha256","checksum_storage_key","signature_format","signature_storage_key","signing_key_id","created_by","created_at","signed_at","completed_at"],"reviewedIncluded":["token_id"],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "recovery_readiness": tablePolicy("org_id", {"included":["id","org_id","device_id","readiness_score","estimated_rto_minutes","estimated_rpo_minutes","calculated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["risk_factors"]}),
  "recovery_tokens": tablePolicy("org_id", {"included":["id","org_id","device_id","snapshot_id","restore_type","status","created_by","created_at","expires_at","authenticated_at","completed_at","used_at"],"reviewedIncluded":[],"excludedSensitive":["token_hash"],"excludedOpen":["target_config"]}),
  "remediation_suggestions": tablePolicy("org_id", {"included":["id","org_id","source_type","source_id","device_id","alert_id","anomaly_id","correlation_group_id","rca_id","target_type","script_id","script_template_id","playbook_id","title","rationale","expected_action","risk_tier","status","confidence","target_device_ids","elevation_request_id","tool_execution_id","script_execution_id","playbook_execution_id","edited_by","accepted_by","rejected_by","executed_by","failure_message","created_by","created_at","updated_at","accepted_at","rejected_at","executed_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["evidence","parameters"]}),
  "remote_sessions": tablePolicy("org_id", {"included":["id","device_id","org_id","user_id","type","status","webrtc_offer","webrtc_answer","started_at","ended_at","duration_seconds","bytes_transferred","recording_url","error_message","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["ice_candidates"]}),
  "reports": tablePolicy("org_id", {"included":["id","org_id","name","type","schedule","format","last_generated_at","execution_scope_version","execution_scope_kind","execution_scope_site_ids","execution_scope_user_id","execution_scope_fingerprint","execution_scope_captured_at","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["config"]}),
  "restore_jobs": tablePolicy("org_id", {"included":["id","org_id","snapshot_id","device_id","restore_type","target_path","status","started_at","completed_at","restored_size","restored_files","initiated_by","command_id","created_at","updated_at"],"reviewedIncluded":["recovery_token_id"],"excludedSensitive":[],"excludedOpen":["selected_paths","target_config"],"specific":{"restore_type_v2":{"decision":"include","rationale":"Versioned restore-type discriminator describes the tenant-owned restore operation and is required to interpret exported restore-job records."}}}),
  "roles": tablePolicy("org_id", {"included":["id","partner_id","org_id","parent_role_id","scope","name","description","is_system","created_at","updated_at"],"reviewedIncluded":["force_mfa"],"excludedSensitive":[],"excludedOpen":[]}),
  "s1_actions": tablePolicy("org_id", {"included":["id","org_id","device_id","requested_by","action","status","provider_action_id","requested_at","completed_at","error"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["payload"]}),
  "s1_agents": tablePolicy("org_id", {"included":["id","org_id","integration_id","s1_agent_id","device_id","status","infected","threat_count","policy_name","last_seen_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "s1_integrations": tablePolicy("org_id", {"included":["id","partner_id","org_id","name","management_url","is_active","last_sync_at","last_sync_status","last_sync_error","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["api_token_encrypted"],"excludedOpen":[]}),
  "s1_org_mappings": tablePolicy("org_id", {"included":["id","integration_id","partner_id","s1_site_id","s1_site_name","org_id","agents_count","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["registration_token"],"excludedOpen":["metadata"]}),
  "s1_site_mappings": tablePolicy("org_id", {"included":["id","integration_id","site_name","org_id","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "s1_threats": tablePolicy("org_id", {"included":["id","org_id","integration_id","device_id","s1_threat_id","classification","severity","threat_name","process_name","file_path","status","detected_at","resolved_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["mitre_tactics","details"]}),
  "saved_filters": tablePolicy("org_id", {"included":["id","org_id","name","description","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["conditions"]}),
  "saved_queries": tablePolicy("org_id", {"included":["id","org_id","name","description","metric_types","metric_names","aggregation","group_by","is_shared","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["filters","time_range"]}),
  "script_categories": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","icon","color","parent_id","order","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "script_execution_batches": tablePolicy("org_id", {"included":["id","script_id","org_id","triggered_by","trigger_type","devices_targeted","devices_completed","devices_failed","status","created_at","completed_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["parameters"]}),
  "script_executions": tablePolicy("org_id", {"included":["id","script_id","device_id","org_id","triggered_by","trigger_type","automation_run_id","status","started_at","completed_at","exit_code","stdout","stderr","error_message","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["parameters"]}),
  "script_tags": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","color"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "scripts": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","category","os_types","language","content","timeout_seconds","run_as","is_system","version","created_by","created_at","updated_at","deleted_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["parameters","exit_code_severity_mapping"]}),
  "security_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","is_default","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["settings"]}),
  "security_posture_org_snapshots": tablePolicy("org_id", {"included":["id","org_id","captured_at","overall_score","devices_audited","low_risk_devices","medium_risk_devices","high_risk_devices","critical_risk_devices","patch_compliance_score","encryption_score","av_health_score","firewall_score","open_ports_score","os_currency_score","admin_exposure_score"],"reviewedIncluded":["password_policy_score"],"excludedSensitive":[],"excludedOpen":["top_issues","summary"]}),
  "security_posture_snapshots": tablePolicy("org_id", {"included":["id","org_id","device_id","captured_at","overall_score","risk_level","patch_compliance_score","encryption_score","av_health_score","firewall_score","open_ports_score","os_currency_score","admin_exposure_score"],"reviewedIncluded":["password_policy_score"],"excludedSensitive":[],"excludedOpen":["factor_details","recommendations"]}),
  "security_scans": tablePolicy("org_id", {"included":["id","device_id","org_id","scan_type","status","started_at","completed_at","items_scanned","threats_found","duration","initiated_by"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "security_status": tablePolicy("org_id", {"included":["id","device_id","org_id","provider","provider_version","definitions_version","definitions_date","real_time_protection","last_scan","last_scan_type","threat_count","firewall_enabled","encryption_status","gatekeeper_enabled","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["encryption_details","local_admin_summary","password_policy_summary"]}),
  "security_threats": tablePolicy("org_id", {"included":["id","device_id","org_id","provider","threat_name","threat_type","severity","status","file_path","process_name","detected_at","resolved_at","resolved_by"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "sensitive_data_findings": tablePolicy("org_id", {"included":["id","org_id","device_id","scan_id","file_path","data_type","pattern_id","match_count","risk","confidence","file_owner","file_modified_at","first_seen_at","last_seen_at","occurrence_count","status","remediation_action","remediated_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["remediation_metadata"]}),
  "sensitive_data_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","is_active","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["scope","detection_classes","schedule"]}),
  "sensitive_data_scans": tablePolicy("org_id", {"included":["id","org_id","device_id","policy_id","requested_by","status","started_at","completed_at","idempotency_key","request_fingerprint","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["summary"]}),
  "service_principals": tablePolicy("org_id", {"included":["id","org_id","name","status","created_by","last_updated_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["scopes"]}),
  "service_process_check_results": tablePolicy("org_id", {"included":["id","org_id","device_id","watch_type","name","status","cpu_percent","memory_mb","pid","auto_restart_attempted","auto_restart_succeeded","timestamp"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "sites": tablePolicy("org_id", {"included":["id","org_id","name","timezone","created_at","updated_at","partner_export_updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["address","contact","settings"]}),
  "sla_compliance": tablePolicy("org_id", {"included":["id","sla_id","org_id","period_start","period_end","uptime_actual","response_time_actual","resolution_time_actual","uptime_compliant","response_time_compliant","resolution_time_compliant","overall_compliant","total_downtime_minutes","incident_count","excluded_minutes","calculated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "sla_definitions": tablePolicy("org_id", {"included":["id","org_id","name","description","uptime_target","response_time_target","resolution_time_target","measurement_window","exclude_maintenance_windows","exclude_weekends","target_type","target_ids","enabled","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "snmp_devices": tablePolicy("org_id", {"included":["id","org_id","asset_id","name","ip_address","snmp_version","port","auth_protocol","priv_protocol","username","polling_interval","template_id","is_active","last_polled","last_poll_attempted_at","consecutive_failures","last_status","created_at"],"reviewedIncluded":[],"excludedSensitive":["community","auth_password","priv_password"],"excludedOpen":[]}),
  "snmp_metrics": tablePolicy("org_id", {"included":["id","device_id","org_id","oid","name","value","value_type","timestamp"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "snmp_templates": tablePolicy("org_id", {"included":["id","org_id","name","description","vendor","device_type","is_built_in","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["oids"]}),
  "software_catalog": tablePolicy("org_id", {"included":["id","org_id","partner_id","integration_provider","name","vendor","description","category","icon_url","website_url","is_managed","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "software_deployments": tablePolicy("org_id", {"included":["id","org_id","name","software_version_id","deployment_type","target_type","schedule_type","scheduled_at","dispatched_at","maintenance_window_id","created_by","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["target_ids","options"]}),
  "software_inventory": tablePolicy("org_id", {"included":["id","device_id","org_id","catalog_id","name","version","vendor","install_date","install_location","uninstall_string","is_managed","last_seen"],"reviewedIncluded":["file_hash","hash_algorithm"],"excludedSensitive":[],"excludedOpen":[]}),
  "software_policies": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","description","mode","target_type","priority","is_active","enforce_mode","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["rules","target_ids","remediation_options"]}),
  "software_policy_audit": tablePolicy("org_id", {"included":["id","org_id","partner_id","policy_id","device_id","action","actor","actor_id","timestamp"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "software_upload_sessions": tablePolicy("org_id", {"included":["id","org_id","catalog_id","file_name","file_size","chunk_size","bytes_received","status","temp_path","owner_instance_id","created_by","created_at","last_activity_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["version_metadata"]}),
  "sql_instances": tablePolicy("org_id", {"included":["id","org_id","device_id","instance_name","version","edition","port","auth_type","status","last_discovered_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["databases"]}),
  "sso_providers": tablePolicy("org_id", {"included":["id","org_id","partner_id","name","type","status","issuer","client_id","userinfo_url","jwks_url","scopes","entity_id","sso_url","certificate","default_role_id","allowed_domains","enforce_sso","config_version","default_role_configured_by","created_by","created_at","updated_at"],"reviewedIncluded":["authorization_url","token_url","auto_provision","trusts_idp_mfa"],"excludedSensitive":["client_secret"],"excludedOpen":["attribute_mapping"]}),
  "sso_verified_domains": tablePolicy("org_id", {"included":["id","org_id","domain","verified_at","last_checked_at","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["verification_token"],"excludedOpen":[]}),
  "storage_encryption_keys": tablePolicy("org_id", {"included":["id","org_id","name","key_type","public_key_pem","is_active","created_at","rotated_at","expires_at"],"reviewedIncluded":[],"excludedSensitive":["encrypted_private_key","key_hash"],"excludedOpen":[]}),
  // code_hash is the verifier for the one-time Quick Support code — credential
  // material, never exported. claimed_from_ip is the end user's IP, which is
  // ordinary tenant record data (mirrors devices.enrollment_ip / last_seen_ip).
  "support_sessions": tablePolicy("org_id", {"included":["id","org_id","created_by_user_id","code_expires_at","status","hard_expires_at","device_id","attributed_org_id","attribution_label","claimed_at","claimed_from_ip","ended_at","ended_reason","created_at"],"reviewedIncluded":[],"excludedSensitive":["code_hash"],"excludedOpen":[]}),
  "ticket_alert_links": tablePolicy("org_id", {"included":["id","ticket_id","org_id","alert_id","link_type","created_by","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "ticket_form_org_links": tablePolicy("org_id", {"included":["id","form_id","org_id","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "ticket_forms": tablePolicy("org_id", {"included":["id","partner_id","org_id","name","description","category_id","title_template","description_intro","default_priority","default_tags","show_in_portal","is_active","sort_order","version","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["fields"]}),
  "ticket_parts": tablePolicy("org_id", {"included":["id","ticket_id","org_id","description","part_number","vendor","quantity","unit_price","cost_basis","is_billable","billing_status","added_by","catalog_item_id","notes","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "tickets": tablePolicy("org_id", {"included":["id","org_id","ticket_number","submitted_by","submitter_email","submitter_name","subject","description","category","status","priority","assigned_to","assigned_team","device_id","tags","external_ticket_id","external_ticket_url","first_response_at","resolved_at","closed_at","partner_id","category_id","pending_reason","due_date","response_sla_minutes","resolution_sla_minutes","sla_breached_at","sla_breach_reason","sla_paused_at","sla_paused_minutes","source","internal_number","email_message_id","email_thread_key","closed_by","resolution_note","status_id","deleted_at","deleted_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["custom_fields"]}),
  "time_entries": tablePolicy("org_id", {"included":["id","partner_id","org_id","ticket_id","user_id","started_at","ended_at","duration_minutes","description","is_billable","hourly_rate","billing_status","is_approved","approved_by","approved_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "time_series_metrics": tablePolicy("org_id", {"included":["timestamp","org_id","device_id","metric_type","metric_name","value","unit"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["tags"]}),
  "topology_layout": tablePolicy("org_id", {"included":["id","org_id","site_id","node_type","node_id","x","y","pinned","updated_by","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "topology_manual_nodes": tablePolicy("org_id", {"included":["id","org_id","site_id","label","role","notes","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "tunnel_allowlists": tablePolicy("org_id", {"included":["id","org_id","site_id","direction","pattern","description","enabled","source","discovered_asset_id","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "tunnel_sessions": tablePolicy("org_id", {"included":["id","device_id","user_id","org_id","type","status","target_host","target_port","scheme","skip_tls_verify","source_ip","bytes_sent","bytes_recv","started_at","ended_at","duration_seconds","error_message","created_at","last_activity_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "unifi_clients": tablePolicy("org_id", {"included":["id","collector_id","org_id","site_id","mac","hostname","ip_address","connected_device_id","uplink_port_idx","is_wired","ssid","vlan","signal_dbm","tx_bytes","rx_bytes","uptime_seconds","discovered_asset_id","is_stale","first_seen_at","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["raw"]}),
  "unifi_collectors": tablePolicy("org_id", {"included":["id","integration_id","org_id","site_id","unifi_host_id","collector_device_id","controller_url","is_enabled","poll_interval_seconds","status","firmware_ok","last_poll_at","last_poll_status","last_poll_error","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["local_api_key_encrypted"],"excludedOpen":[]}),
  "unifi_controller_sites": tablePolicy("org_id", {"included":["id","collector_id","org_id","local_site_id","name","last_seen_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "unifi_device_telemetry": tablePolicy("org_id", {"included":["id","collector_id","org_id","site_id","unifi_device_id","mac","name","uptime_seconds","cpu_pct","mem_pct","tx_bytes","rx_bytes","num_clients","discovered_asset_id","is_stale","last_seen_at","first_synced_at","last_synced_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["poe_ports","raw"]}),
  "unifi_devices": tablePolicy("org_id", {"included":["id","org_id","site_id","integration_id","mapping_id","discovered_asset_id","unifi_device_id","mac","name","model","device_type","ip_address","firmware_version","firmware_updatable","adoption_state","uptime_seconds","is_stale","last_seen_at","first_synced_at","last_synced_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["raw"]}),
  "unifi_site_mappings": tablePolicy("org_id", {"included":["id","integration_id","org_id","site_id","unifi_host_id","unifi_site_id","unifi_host_name","unifi_site_name","wan_metrics_at","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["wan_metrics"]}),
  "user_notifications": tablePolicy("org_id", {"included":["id","user_id","org_id","type","priority","title","message","link","read","read_at","created_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["metadata"]}),
  "user_risk_events": tablePolicy("org_id", {"included":["id","org_id","user_id","event_type","severity","score_impact","description","occurred_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["details"]}),
  "user_risk_policies": tablePolicy("org_id", {"included":["id","org_id","updated_by","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["weights","thresholds","interventions"]}),
  "user_risk_scores": tablePolicy("org_id", {"included":["id","org_id","user_id","score","trend_direction","calculated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["factors"]}),
  "users": tablePolicy("org_id", {"included":["id","partner_id","org_id","email","name","phone_number","phone_verified","status","disabled_reason","avatar_url","avatar_mime","avatar_updated_at","last_login_at","setup_completed_at","email_verified_at","is_platform_admin","auth_epoch","permissions_epoch","email_epoch","pending_email","pending_email_requested_at","created_at","updated_at"],"reviewedIncluded":["mfa_enabled","mfa_method","password_changed_at","mfa_epoch","password_reset_epoch"],"excludedSensitive":["password_hash","mfa_secret","mfa_recovery_codes"],"excludedOpen":["preferences","avatar_data"]}),
  "vault_snapshot_inventory": tablePolicy("org_id", {"included":["id","org_id","vault_id","snapshot_db_id","external_snapshot_id","synced_at","size_bytes","file_count","manifest_verified","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":[]}),
  "webhooks": tablePolicy("org_id", {"included":["id","org_id","name","events","status","success_count","failure_count","last_delivery_at","last_success_at","created_by","created_at","updated_at"],"reviewedIncluded":[],"excludedSensitive":["url","secret"],"excludedOpen":["headers","retry_policy"]}),
  "organizations": tablePolicy("id", {"included":["id","partner_id","name","slug","type","status","max_devices","contract_start","contract_end","tax_id","tax_exempt","tax_rate","billing_address_line1","billing_address_line2","billing_address_city","billing_address_region","billing_address_postal_code","billing_address_country","created_at","updated_at","partner_export_updated_at","offboarding_started_at","deleted_at"],"reviewedIncluded":[],"excludedSensitive":[],"excludedOpen":["settings","sso_config","billing_contact"]}),
};

function equivalentDecisions(
  left: TenantExportTablePolicy,
  right: TenantExportTablePolicy,
): boolean {
  const decisions = (policy: TenantExportTablePolicy) => Object.entries(policy.columns)
    .map(([name, value]) => [name, value.decision] as const)
    .sort(([leftName], [rightName]) => leftName.localeCompare(rightName));
  return left.organizationKey === right.organizationKey
    && JSON.stringify(decisions(left)) === JSON.stringify(decisions(right));
}

function extensionPolicy(
  include: readonly string[],
  exclude: readonly string[],
): TenantExportTablePolicy {
  const columns: Record<string, ExportColumnDecision> = {};
  for (const column of include) {
    columns[column] = {
      decision: 'include',
      rationale: 'Extension manifest explicitly includes this reviewed tenant-export column.',
      reviewedSensitiveName: true,
      openContainerReviewed: true,
    };
  }
  for (const column of exclude) {
    columns[column] = {
      decision: 'exclude',
      rationale: 'Extension manifest explicitly excludes this reviewed tenant-export column.',
      reviewedSensitiveName: true,
      openContainerReviewed: true,
    };
  }
  return { organizationKey: 'org_id', columns };
}

/** Build a fresh registry so runtime extension registrations are visible to every export. */
export function getTenantExportPolicyRegistry(): TenantExportPolicyRegistry {
  const registry: Record<string, TenantExportTablePolicy> = {
    ...CORE_TENANT_EXPORT_POLICY,
  };
  for (const [table, declaration] of Object.entries(getExtensionOrgExportColumns())) {
    const policy = extensionPolicy(declaration.include, declaration.exclude);
    const existing = registry[table];
    if (existing && !equivalentDecisions(existing, policy)) {
      throw new Error(
        `[tenantExport] extension table "${table}" conflicts with the core export classification`,
      );
    }
    registry[table] ??= policy;
  }
  return registry;
}
